### ISSUE TITLE
CpiwBypa problem

### ISSUE THREAD

**Issue by Neustradamus** [YuZhouRen86/VxKex-NEXT#217]
Dear all, @i486, @YuZhouRen86,

There is a problem with "CpiwBypa" which is included in VxKex:
- https://github.com/search?q=CpiwBypa&type=issues

When we launch applications, we can have: "APPLICATION.exe is not a valid Win32 application."
- https://github.com/i486/VxKex/issues/183
- https://github.com/YuZhouRen86/VxKex-NEXT/issues/141
- https://github.com/i486/VxKex/issues/177
- https://github.com/YuZhouRen86/VxKex-NEXT/issues/140

Other:
- https://github.com/search?q=%22is+not+a+valid+Win32+application%22&type=issues
- https://github.com/search?q=repo%3Ai486%2FVxKex+is+not+a+valid+Win32+application&type=issues
- https://github.com/search?q=repo%3AYuZhouRen86%2FVxKex-NEXT+is+not+a+valid+Win32+application&type=issues

Any help is welcome to solve this problem.

Linked to:
- https://github.com/i486/VxKex/issues/211
- https://github.com/YuZhouRen86/VxKex-NEXT/issues/217

**Comment by YuZhouRen86** [comment]
Fixed in the latest version.

**Comment by ask2018** [comment]
@YuZhouRen86 this is unfortunately still not fully fixed in latest version.  I'm still getting the "Not a valid Win32 application" error without the winvertroll patch for example on [ElectronMail](https://github.com/vladimiry/ElectronMail/).

**Comment by ask2018** [comment]
@YuZhouRen86 some update to this. If I restarted PC, then it works from desktop shortcut (the CpiwBypaLdr.exe has not been loaded without restart - maybe installer should load it), but it still doesn't work if I run it in Total Commander. That is how I normally work with files, so I don't consider it fully fixed. If it is problematic to do it if it is not loaded via explorer, then I suggest adding similar patching function as winvertroll has as an option in VxKex.

**Comment by YuZhouRen86** [comment]
> @YuZhouRen86 some update to this. If I restarted PC, then it works from desktop shortcut (the CpiwBypaLdr.exe has not been loaded without restart - maybe installer should load it), but it still doesn't work if I run it in Total Commander. That is how I normally work with files, so I don't consider it fully fixed. If it is problematic to do it if it is not loaded via explorer, then I suggest adding similar patching function as winvertroll has as an option in VxKex.

The installer added a scheduled task which loads CpiwBypaLdr.exe after user logging on the system. If you log out and log on, it will be loaded. The installer should not load it, because if installer load CpiwBypaLdr.exe after installing VxKex NEXT and user do uninstall and install many times, there will be multiple running CpiwBypaLdr.exe.
You can enable VxKex NEXT for Total Commander, and this will bypass the error.

How is the new Czech translation? Additionally, in the new version, Slovak language will be fallback to Czech, as we think the relationship between Czech and Slovak language is similar to Simplified and Traditional Chinese.

**Comment by ask2018** [comment]
> > [@YuZhouRen86](https://github.com/YuZhouRen86) some update to this. If I restarted PC, then it works from desktop shortcut (the CpiwBypaLdr.exe has not been loaded without restart - maybe installer should load it), but it still doesn't work if I run it in Total Commander. That is how I normally work with files, so I don't consider it fully fixed. If it is problematic to do it if it is not loaded via explorer, then I suggest adding similar patching function as winvertroll has as an option in VxKex.
> 
> The installer added a scheduled task which loads CpiwBypaLdr.exe after user logging on the system. If you log out and log on, it will be loaded. The installer should not load it, because if installer load CpiwBypaLdr.exe after installing VxKex NEXT and user do uninstall and install many times, there will be multiple running CpiwBypaLdr.exe. You can enable VxKex NEXT for Total Commander, and this will bypass the error.
> 
> How is the new Czech translation? Additionally, in the new version, Slovak language will be fallback to Czech, as we think the relationship between Czech and Slovak language is similar to Simplified and Traditional Chinese.

Sorry for late reply. I somehow missed your message. 

I see. Thanks for explanation. Are you sure it is really safe to enable VxKex for Total Commander? Because that is the software I'm using for all file operations and any error there will be critical. In general I prefer here just patching the file with winvertroll, but I thought it would be better and more user friendly if such function is part of VxKex itself. But if you don’t want to add it as VxKex function, winvertroll is fine for me as well.

The Czech translation seems to be ok. Just it would be maybe good if the user can choose the language there also manually. It is better for testing and reporting problems to have English language screenshots.

I’m not expert on Chinese, but I don’t think this is good comparison. Slovak is separate language, but it is very similar to Czech and we can understand each other very well without any translation while speaking, listening, writing or reading. But yep I’m sure some people might be happy if Slovak is as well supported.

**Comment by ask2018** [comment]
@YuZhouRen86 did you make any changes in version 1.2.0.2222 related to Total Commander?

**Comment by YuZhouRen86** [comment]
> @YuZhouRen86 did you make any changes in version 1.2.0.2222 related to Total Commander?

No, Total Commander is not a system application, and it does not need any app-specific hack. Total Commander latest version works correctly on my Windows 7 computer with VxKex NEXT enabled. If you set display scaling factor to 125% and up, it has a window scaling problem (the size of window is too big), but this problem is already fixed in the testing version and the fix will be included in next release version.

**Comment by ask2018** [comment]
> > [@YuZhouRen86](https://github.com/YuZhouRen86) did you make any changes in version 1.2.0.2222 related to Total Commander?
> 
> No, Total Commander is not a system application, and it does not need any app-specific hack. Total Commander latest version works correctly on my Windows 7 computer with VxKex NEXT enabled. If you set display scaling factor to 125% and up, it has a window scaling problem (the size of window is too big), but this problem is already fixed in the testing version and the fix will be included in next release version.

I'm asking because Total Commander started crashing when I upgraded VxKex frm 1.2.0.2202 to 1.2.0.2222. And I dont have VxKex enabled for Total Commander at all. I needed to downgrade VxKex back to version 1.2.0.2202. There must be some change related to it.

**Comment by YuZhouRen86** [comment]
> > No, Total Commander is not a system application, and it does not need any app-specific hack. Total Commander latest version works correctly on my Windows 7 computer with VxKex NEXT enabled. If you set display scaling factor to 125% and up, it has a window scaling problem (the size of window is too big), but this problem is already fixed in the testing version and the fix will be included in next release version.
> 
> I'm asking because Total Commander started crashing when I upgraded VxKex frm 1.2.0.2202 to 1.2.0.2222. And I dont have VxKex enabled for Total Commander at all. I needed to downgrade VxKex back to version 1.2.0.2202. There must be some change related to it.

I don't think the problem is related to VxKex NEXT. On my computer Total Commander works correctly. Windows 7 64 bit Simplified Chinese, ESU until Nov. 2025, Administrator account, VxKex NEXT 1.2.0.2222. And nothing was changed related to Total Commander in VxKex NEXT 1.2.0.2222.

**Comment by ask2018** [comment]
> > > No, Total Commander is not a system application, and it does not need any app-specific hack. Total Commander latest version works correctly on my Windows 7 computer with VxKex NEXT enabled. If you set display scaling factor to 125% and up, it has a window scaling problem (the size of window is too big), but this problem is already fixed in the testing version and the fix will be included in next release version.
> > 
> > 
> > I'm asking because Total Commander started crashing when I upgraded VxKex frm 1.2.0.2202 to 1.2.0.2222. And I dont have VxKex enabled for Total Commander at all. I needed to downgrade VxKex back to version 1.2.0.2202. There must be some change related to it.
> 
> I don't think the problem is related to VxKex NEXT. On my computer Total Commander works correctly. Windows 7 64 bit Simplified Chinese, ESU until Nov. 2025, Administrator account, VxKex NEXT 1.2.0.2222. And nothing was changed related to Total Commander in VxKex NEXT 1.2.0.2222.

The problem is 100% related to VxKex NEXT. I never see Total Commander crashed and It started right after I updated  to VxKex NEXT 1.2.0.2222 (crashed every few minutes) and dissapeard right after I removed this version and downgraded to 1.2.0.2202. But the question is why this is happening if you say nothing was changed related to Total Commander in VxKex NEXT 1.2.0.2222.

**Comment by ask2018** [comment]
Also @YuZhouRen86 recheck this please https://github.com/YuZhouRen86/VxKex-NEXT/issues/75#issuecomment-4895225388 There really needs to be safe and quick way how to downgrade VxKex NEXT and keep application settings for similar cases when something critical breaks in new version and as well for tests and debugging. I cannot even retest this, because it means again 30 minutes of work setting up everything again from scratch.

**Comment by YuZhouRen86** [comment]
> The problem is 100% related to VxKex NEXT. I never see Total Commander crashed and It started right after I updated  to VxKex NEXT 1.2.0.2222 (crashed every few minutes) and dissapeard right after I removed this version and downgraded to 1.2.0.2202. But the question is why this is happening if you say nothing was changed related to Total Commander in VxKex NEXT 1.2.0.2222.

KexShlEx.dll and KexShl32.dll, which is the explorer extension, was changed, to load KexMLS translation module. And I think it caused the crash problem in explorer-related applications. This morning, I encountered the issue where Everything (file searching tool) crashed. Sincerely apologize for this serious bug.

**Comment by ask2018** [comment]
> > The problem is 100% related to VxKex NEXT. I never see Total Commander crashed and It started right after I updated  to VxKex NEXT 1.2.0.2222 (crashed every few minutes) and dissapeard right after I removed this version and downgraded to 1.2.0.2202. But the question is why this is happening if you say nothing was changed related to Total Commander in VxKex NEXT 1.2.0.2222.
> 
> KexShlEx.dll and KexShl32.dll, which is the explorer extension, was changed, to load KexMLS translation module. And I think it caused the crash problem in explorer-related applications. This morning, I encountered the issue where Everything (file searching tool) crashed. Sincerely apologize for this serious bug.

That is higly possible that this is the cause of the issue, because if I'm thinking about it more, I've been loading the right click menu from Explorer in Total Commander when the crash started. And yeah bugs might happen. Good we catched it.

**Comment by YuZhouRen86** [comment]
> Also @YuZhouRen86 recheck this please https://github.com/YuZhouRen86/VxKex-NEXT/issues/75#issuecomment-4895225388 There really needs to be safe and quick way how to downgrade VxKex NEXT and keep application settings for similar cases when something critical breaks in new version and as well for tests and debugging. I cannot even retest this, because it means again 30 minutes of work setting up everything again from scratch.

To backup the settings of VxKex NEXT enabled apps manually, you can export HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options registry key and merge it after downgrading. We have adopted your suggestion, the feature that saving information of VxKex NEXT enabled apps and restore after reinstalling is in our plan. But I (the primary developer now) will be very very busy until August 2027. I will try to fix the bugs in the current version and add this feature.
Thank you very much.

**Comment by YuZhouRen86** [comment]
> That is higly possible that this is the cause of the issue, because if I'm thinking about it more, I've been loading the right click menu from Explorer in Total Commander when the crash started. And yeah bugs might happen. Good we catched it.

The test versions of vxiiduu VxKex are released in his Discord group, but in China mainland, these mainstream Western media are blocked. I also want to find a suitable channel to release the test versions.

Do you have VK? This is the platform I communicate with vxiiduu, and it is avaliable here in mainland China.

**Comment by ask2018** [comment]
> > That is higly possible that this is the cause of the issue, because if I'm thinking about it more, I've been loading the right click menu from Explorer in Total Commander when the crash started. And yeah bugs might happen. Good we catched it.
> 
> The test versions of vxiiduu VxKex are released in his Discord group, but in China mainland, these mainstream Western media are blocked. I also want to find a suitable channel to release the test versions.
> 
> Do you have VK? This is the platform I communicate with vxiiduu, and it is avaliable here in mainland China.

I don't have Discord nor VK. I preffer platforms not tied to web or mobile phones numbers like irc or simple email.

**Comment by YuZhouRen86** [comment]
> I don't have Discord nor VK. I preffer preffer platforms not tied to web or mobile phones numbers like irc or simple email.

I will create a VxKex NEXT public beta repo in gitee (a platform similar to GitHub but is very fast in China, GitHub access is extremely slow here), and release the test versions there. Our Gitee Homepage is https://gitee.com/YuZhouRen86. A Chinese phone number is required to register, but you can download files without registration.

**Comment by ask2018** [comment]
>  I also want to find a suitable channel to release the test versions.

Why not to publish test versions on Github or Gitee? It should be just marked as dev test version, but much more people can test it, if its public and not inside some obscure network where you need to register with SMS verification and might be blocked in some countries.

**Comment by ask2018** [comment]
> > I don't have Discord nor VK. I preffer preffer platforms not tied to web or mobile phones numbers like irc or simple email.
> 
> I will create a VxKex NEXT public beta repo in gitee (a platform similar to GitHub but is very fast in China, GitHub access is extremely slow here), and release the test versions there. Our Gitee Homepage is https://gitee.com/YuZhouRen86. A Chinese phone number is required to register, but you can download files without registration.

Yes I have this in my bookmarks as well. If the files can be downloaded without registration, then its ok. But in general it is good to avoid any platform tied to some SMS verification. Such platforms are simply no go for me and anybody else who cares about privacy.

**Comment by YuZhouRen86** [comment]
> That is higly possible that this is the cause of the issue, because if I'm thinking about it more, I've been loading the right click menu from Explorer in Total Commander when the crash started. And yeah bugs might happen. Good we catched it.

Please backup the IFEO options registry and update to version 1.2.0.2226. It fixed the explorer crash bug.

**Comment by ask2018** [comment]
> > That is higly possible that this is the cause of the issue, because if I'm thinking about it more, I've been loading the right click menu from Explorer in Total Commander when the crash started. And yeah bugs might happen. Good we catched it.
> 
> Please backup the IFEO options registry and update to version 1.2.0.2226. It fixed the explorer crash bug.

I'm testing it and seems to be without Total Commander crashes for now. I've tried also PC restart and still no crash. Thank you. I'll report here if I'll notice any crashes. I just still have the odd Brave issue I mentioned here on my main system - https://github.com/YuZhouRen86/VxKex-NEXT/issues/369#issuecomment-4900115889
